# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Some Notes
description: > # Just some random notes of mine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://notes.whitepinedev.com" # the base hostname & protocol for your site
twitter_username: chickenfur
github_username:  chickenfur

# Build settings
markdown: kramdown
